print("====== DESAFIO 004 ======")
algo = input("Digite algo: ")
print("{} é númerico? ".format(algo))
print(algo.isnumeric())
print("{} é alfabético? ".format(algo))
print(algo.isalpha())
print("{} é minúsculo? ".format(algo))
print(algo.islower())
print("{} é maiúsculo? ".format(algo))
print(algo.isupper())
print("{} é um space? ".format(algo))
print(algo.isspace())
